sudo: required

services: docker
before_install:
  - gem install bundler
  - docker-compose up -d

script:
  - docker-compose exec --env'RAILS_ENV=test' web rails dc:create
  - docker-compose exec --env'RAILS_ENV=test' web rails dc:migrate
  - docker-compose exec --env'RAILS_ENV=test' web rails test